# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/pi/projet_tristan/projet

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/pi/projet_tristan/projet

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/local/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/projet_tristan/projet/CMakeFiles /home/pi/projet_tristan/projet/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/pi/projet_tristan/projet/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named projet_imu

# Build rule for target.
projet_imu: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 projet_imu
.PHONY : projet_imu

# fast build rule for target.
projet_imu/fast:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/build
.PHONY : projet_imu/fast

Control_JACO.o: Control_JACO.cpp.o

.PHONY : Control_JACO.o

# target to build an object file
Control_JACO.cpp.o:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/Control_JACO.cpp.o
.PHONY : Control_JACO.cpp.o

Control_JACO.i: Control_JACO.cpp.i

.PHONY : Control_JACO.i

# target to preprocess a source file
Control_JACO.cpp.i:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/Control_JACO.cpp.i
.PHONY : Control_JACO.cpp.i

Control_JACO.s: Control_JACO.cpp.s

.PHONY : Control_JACO.s

# target to generate assembly for a file
Control_JACO.cpp.s:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/Control_JACO.cpp.s
.PHONY : Control_JACO.cpp.s

Dislin_Scope.o: Dislin_Scope.cpp.o

.PHONY : Dislin_Scope.o

# target to build an object file
Dislin_Scope.cpp.o:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/Dislin_Scope.cpp.o
.PHONY : Dislin_Scope.cpp.o

Dislin_Scope.i: Dislin_Scope.cpp.i

.PHONY : Dislin_Scope.i

# target to preprocess a source file
Dislin_Scope.cpp.i:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/Dislin_Scope.cpp.i
.PHONY : Dislin_Scope.cpp.i

Dislin_Scope.s: Dislin_Scope.cpp.s

.PHONY : Dislin_Scope.s

# target to generate assembly for a file
Dislin_Scope.cpp.s:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/Dislin_Scope.cpp.s
.PHONY : Dislin_Scope.cpp.s

EMG_Sensor.o: EMG_Sensor.cpp.o

.PHONY : EMG_Sensor.o

# target to build an object file
EMG_Sensor.cpp.o:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/EMG_Sensor.cpp.o
.PHONY : EMG_Sensor.cpp.o

EMG_Sensor.i: EMG_Sensor.cpp.i

.PHONY : EMG_Sensor.i

# target to preprocess a source file
EMG_Sensor.cpp.i:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/EMG_Sensor.cpp.i
.PHONY : EMG_Sensor.cpp.i

EMG_Sensor.s: EMG_Sensor.cpp.s

.PHONY : EMG_Sensor.s

# target to generate assembly for a file
EMG_Sensor.cpp.s:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/EMG_Sensor.cpp.s
.PHONY : EMG_Sensor.cpp.s

IMU_Sensor.o: IMU_Sensor.cpp.o

.PHONY : IMU_Sensor.o

# target to build an object file
IMU_Sensor.cpp.o:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/IMU_Sensor.cpp.o
.PHONY : IMU_Sensor.cpp.o

IMU_Sensor.i: IMU_Sensor.cpp.i

.PHONY : IMU_Sensor.i

# target to preprocess a source file
IMU_Sensor.cpp.i:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/IMU_Sensor.cpp.i
.PHONY : IMU_Sensor.cpp.i

IMU_Sensor.s: IMU_Sensor.cpp.s

.PHONY : IMU_Sensor.s

# target to generate assembly for a file
IMU_Sensor.cpp.s:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/IMU_Sensor.cpp.s
.PHONY : IMU_Sensor.cpp.s

exception.o: exception.cpp.o

.PHONY : exception.o

# target to build an object file
exception.cpp.o:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/exception.cpp.o
.PHONY : exception.cpp.o

exception.i: exception.cpp.i

.PHONY : exception.i

# target to preprocess a source file
exception.cpp.i:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/exception.cpp.i
.PHONY : exception.cpp.i

exception.s: exception.cpp.s

.PHONY : exception.s

# target to generate assembly for a file
exception.cpp.s:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/exception.cpp.s
.PHONY : exception.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/main.cpp.s
.PHONY : main.cpp.s

mySerial.o: mySerial.cpp.o

.PHONY : mySerial.o

# target to build an object file
mySerial.cpp.o:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/mySerial.cpp.o
.PHONY : mySerial.cpp.o

mySerial.i: mySerial.cpp.i

.PHONY : mySerial.i

# target to preprocess a source file
mySerial.cpp.i:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/mySerial.cpp.i
.PHONY : mySerial.cpp.i

mySerial.s: mySerial.cpp.s

.PHONY : mySerial.s

# target to generate assembly for a file
mySerial.cpp.s:
	$(MAKE) -f CMakeFiles/projet_imu.dir/build.make CMakeFiles/projet_imu.dir/mySerial.cpp.s
.PHONY : mySerial.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... projet_imu"
	@echo "... Control_JACO.o"
	@echo "... Control_JACO.i"
	@echo "... Control_JACO.s"
	@echo "... Dislin_Scope.o"
	@echo "... Dislin_Scope.i"
	@echo "... Dislin_Scope.s"
	@echo "... EMG_Sensor.o"
	@echo "... EMG_Sensor.i"
	@echo "... EMG_Sensor.s"
	@echo "... IMU_Sensor.o"
	@echo "... IMU_Sensor.i"
	@echo "... IMU_Sensor.s"
	@echo "... exception.o"
	@echo "... exception.i"
	@echo "... exception.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... mySerial.o"
	@echo "... mySerial.i"
	@echo "... mySerial.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

