#!/bin/sh
echo ""
echo "     /*****************************************************************/"
echo "     /**                       I N S T A L L                         **/"
echo "     /**                                                             **/"
echo "     /** This program installs the graphics software DISLIN. The va- **/"
echo "     /** riable  DISLIN must be set to  the directory  where  DISLIN **/"
echo "     /** should be installed:                                        **/"
echo "     /** For example:  DISLIN=/usr/local/dislin                      **/"
echo "     /**               export DISLIN                                 **/"
echo "     /**                                                             **/"
echo "     /** Date   : 15.01.2017                                         **/"
echo "     /** Version: 11.0 / Linux, arm                                  **/"
echo "     /*****************************************************************/"
echo ""

if test ${DISLIN} ; then
  echo "Installation of DISLIN in directory "${DISLIN}
  echo ""
else
  echo "The environment DISLIN is not defined!"
  exit 0
fi 

if test ! -d ${DISLIN}; then 
  mkdir ${DISLIN} 
  echo "The directory  "${DISLIN}"      is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}

if test ! -d ${DISLIN}/map; then 
  mkdir ${DISLIN}/map 
  echo "The directory  "${DISLIN}"/map  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/map

if test ! -d ${DISLIN}/man; then 
  mkdir ${DISLIN}/man 
  echo "The directory  "${DISLIN}"/man  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/man

if test ! -d ${DISLIN}/hlp; then 
  mkdir ${DISLIN}/hlp 
  echo "The directory  "${DISLIN}"/hlp  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/hlp

if test ! -d ${DISLIN}/fonts; then 
  mkdir ${DISLIN}/fonts 
  echo "The directory  "${DISLIN}"/fonts  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/fonts

if test ! -d ${DISLIN}/bin; then 
  mkdir ${DISLIN}/bin 
  echo "The directory  "${DISLIN}"/bin  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin

if test ! -d ${DISLIN}/real64; then 
  mkdir ${DISLIN}/real64 
  echo "The directory  "${DISLIN}"/real64 is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin

if test ! -d ${DISLIN}/lib; then 
  mkdir ${DISLIN}/lib 
  echo "The directory  "${DISLIN}"/lib  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/lib

if test ! -d ${DISLIN}/examples; then 
  mkdir ${DISLIN}/examples
  echo "The directory  "${DISLIN}"/examples  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/examples

if test ! -d ${DISLIN}/gf; then 
  mkdir ${DISLIN}/gf
  echo "The directory  "${DISLIN}"/gf  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/gf

if test ! -d ${DISLIN}/gf/real64; then 
  mkdir ${DISLIN}/gf/real64
  echo "The directory  "${DISLIN}"/gf/real64  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/gf/real64

if test ! -d $DISLIN/gcldir; then 
  mkdir $DISLIN/gcldir 
  echo "The directory  "${DISLIN}"/gcldir  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/gcldir

if test ! -d ${DISLIN}/python; then 
  mkdir ${DISLIN}/python 
  echo "The directory  "${DISLIN}"/python  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/python

if test ! -d ${DISLIN}/python3; then 
  mkdir ${DISLIN}/python3 
  echo "The directory  "${DISLIN}"/python3 is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/python3

if test ! -d ${DISLIN}/perl; then 
  mkdir ${DISLIN}/perl 
  echo "The directory  "${DISLIN}"/perl  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/perl

if test ! -d ${DISLIN}/java; then 
  mkdir ${DISLIN}/java 
  echo "The directory  "${DISLIN}"/java  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/java

if test ! -d ${DISLIN}/ruby; then 
  mkdir ${DISLIN}/ruby 
  echo "The directory  "${DISLIN}"/ruby  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/ruby

if test ! -d ${DISLIN}/tcl; then 
  mkdir ${DISLIN}/tcl 
  echo "The directory  "${DISLIN}"/tcl  is created!"
fi
chmod u=rwx,g=rx,o=rx ${DISLIN}/tcl

cp -p man/*.txt ${DISLIN}/man
echo "man/*          is copied to  "${DISLIN}"/man"
cp -p gcldir/man/*    ${DISLIN}/man
echo "gcldir/man/*   is copied to  "${DISLIN}"/man"
chmod u=rw,g=r,o=r ${DISLIN}/man/*

cp -p hlp/*.txt ${DISLIN}/hlp
echo "hlp/*          is copied to  "${DISLIN}"/hlp"
cp -p gcldir/hlp/*    ${DISLIN}/hlp
echo "gcldir/hlp/*   is copied to  "${DISLIN}"/hlp"
chmod u=rw,g=r,o=r ${DISLIN}/hlp/*

cp -p fonts/*.bdf ${DISLIN}/fonts
echo "fonts/*        is copied to  "${DISLIN}"/fonts"
chmod u=rw,g=r,o=r ${DISLIN}/fonts/*

cp -p gcldir/*.gcl ${DISLIN}/gcldir
cp -p gcldir/*.ini ${DISLIN}/gcldir
chmod u=rw,g=r,o=r ${DISLIN}/gcldir/*
echo "gcldir/*.gcl   is copied to  "${DISLIN}"/gcldir"

cp -p python/*  ${DISLIN}/python
echo "python/*       is copied to  "${DISLIN}"/python"
chmod u=rwx,g=rx,o=rx ${DISLIN}/python/*.py

cp -p python3/*  ${DISLIN}/python3
echo "python3/*      is copied to  "${DISLIN}"/python3"
chmod u=rwx,g=rx,o=rx ${DISLIN}/python3/*.py

cp -p perl/*  ${DISLIN}/perl
echo "perl/*         is copied to  "${DISLIN}"/perl"
chmod u=rwx,g=rx,o=rx ${DISLIN}/perl/*
chmod u=rw,g=r,o=r  ${DISLIN}/perl/Dislin.pm

cp -p ruby/*  ${DISLIN}/ruby
echo "ruby/*         is copied to  "${DISLIN}"/ruby"
chmod u=rwx,g=rx,o=rx ${DISLIN}/ruby/*.rb

cp -p tcl/*  ${DISLIN}/tcl
echo "tcl/*          is copied to  "${DISLIN}"/tcl"
chmod u=rwx,g=rx,o=rx ${DISLIN}/tcl/*.tcl

cp -p java/*  ${DISLIN}/java
echo "java/*         is copied to  "${DISLIN}"/java"
chmod u=rwx,g=r,o=r ${DISLIN}/java/*

cp -p linux_arm/bin/*        ${DISLIN}/bin
echo "linux_arm/bin is copied to  "${DISLIN}/"bin"
   
chmod u=rwx,g=x,o=x ${DISLIN}/bin/*
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/disaps
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/disbmp
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/disdrv
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/disgif
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/disimg
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/dismov
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/dispng
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/distif

chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/clink
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/cpplink
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/gf95link
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/gf77link

cp -p ${DISLIN}/bin/gf77link ${DISLIN}/bin/dlink
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/dlink
cp -p ${DISLIN}/bin/gf95link ${DISLIN}/bin/f90link
chmod u=rwx,g=rx,o=rx ${DISLIN}/bin/f90link

cp -p linux_arm/gf/dislin.mod    ${DISLIN}/gf
cp -p linux_arm/gf/dislin_d.mod  ${DISLIN}/gf/real64/dislin.mod
chmod u=rw,g=r,o=r ${DISLIN}/gf/dislin.mod
chmod u=rw,g=r,o=r ${DISLIN}/gf/real64/dislin.mod

cp -p linux_arm/dislin.f90    ${DISLIN}/gf
cp -p linux_arm/dislin_d.f90  ${DISLIN}/gf/real64/dislin.f90

cp -p linux_arm/lib/*        ${DISLIN}/lib
echo "linux_arm/lib is copied to  "${DISLIN}/"lib"
   
chmod u=rw,g=r,o=r ${DISLIN}/lib/*.a
chmod u=rwx,g=rx,o=rx ${DISLIN}/lib/*.so

cp -p linux_arm/perl/*       ${DISLIN}/perl
chmod u=rwx,g=rx,o=rx ${DISLIN}/perl/*.so
cp -p linux_arm/python/* ${DISLIN}/python
chmod u=rwx,g=rx,o=rx ${DISLIN}/python/*.so
cp -p linux_arm/python3/* ${DISLIN}/python3
chmod u=rwx,g=rx,o=rx ${DISLIN}/python3/*.so
cp -p linux_arm/java/* ${DISLIN}/java
chmod u=rwx,g=rx,o=rx ${DISLIN}/java/*.so
cp -p linux_arm/ruby/* ${DISLIN}/ruby
chmod u=rwx,g=rx,o=rx ${DISLIN}/ruby/*.so
cp -p linux_arm/tcl/* ${DISLIN}/tcl
chmod u=rwx,g=rx,o=rx ${DISLIN}/tcl/*.so

if test ! -f ${DISLIN}/dislin.log ; then  
  cp -p dislin.log ${DISLIN}
  chmod u=rw,g=rw,o=rw ${DISLIN}/dislin.log
  echo "dislin.log     is copied to  "${DISLIN}
fi

cp -p map/* ${DISLIN}/map
chmod u=rw,g=r,o=r ${DISLIN}/map/*
echo "map/*          is copied to  "${DISLIN}"/map"

cp -p README ${DISLIN}
chmod u=rw ${DISLIN}/README
echo "README         is copied to  "${DISLIN}

cp -p DISLIN ${DISLIN}
chmod u=rw,g=r,o=r ${DISLIN}/DISLIN
echo "DISLIN         is copied to  "${DISLIN}

cp -p license.txt ${DISLIN}
chmod u=rw,g=r,o=r ${DISLIN}/license.txt
echo "license.txt    is copied to  "${DISLIN}

cp -p examples/dislin.h  ${DISLIN}
cp -p examples/dislin_d.h  ${DISLIN}/real64/dislin.h
cp -p examples/discpp.h  ${DISLIN}
cp -p examples/exa_c.c   ${DISLIN}/examples
cp -p examples/exa_cpp.cpp   ${DISLIN}/examples
cp -p examples/exa_f77.f ${DISLIN}/examples
cp -p examples/map_c.c   ${DISLIN}/examples
cp -p examples/map_cpp.cpp   ${DISLIN}/examples
cp -p examples/map_f77.f ${DISLIN}/examples
cp -p examples/exa_f90.f90 ${DISLIN}/examples
cp -p examples/map_f90.f90 ${DISLIN}/examples

echo "examples/*     is copied to  "${DISLIN}"/examples"
chmod u=rw,g=r,o=r ${DISLIN}/examples/*
chmod u=rw,g=r,o=r ${DISLIN}/dislin.h
chmod u=rw,g=r,o=r ${DISLIN}/real64/dislin.h
chmod u=rw,g=r,o=r ${DISLIN}/discpp.h

ln -s -f ${DISLIN}/lib/dislin-11.0.a     ${DISLIN}/libdislin.a
ln -s -f ${DISLIN}/lib/dislin_d-11.0.a   ${DISLIN}/libdislin_d.a
ln -s -f ${DISLIN}/lib/dislin-11.0.a     ${DISLIN}/libdislnc.a
ln -s -f ${DISLIN}/lib/dislin_d-11.0.a   ${DISLIN}/libdislnc_d.a

ln -s -f ${DISLIN}/lib/dislin-11.0.so    ${DISLIN}/libdislin.so.11
ln -s -f ${DISLIN}/libdislin.so.11       ${DISLIN}/libdislin.so
ln -s -f ${DISLIN}/lib/dislin-11.0.so    ${DISLIN}/libdislnc.so.11
ln -s -f ${DISLIN}/libdislin.so.11       ${DISLIN}/libdislnc.so

ln -s -f ${DISLIN}/lib/discpp-11.0.so    ${DISLIN}/libdiscpp.so.11
ln -s -f ${DISLIN}/libdiscpp.so.11       ${DISLIN}/libdiscpp.so

ln -s -f ${DISLIN}/lib/dislin_d-11.0.so  ${DISLIN}/libdislin_d.so.11
ln -s -f ${DISLIN}/libdislin_d.so.11     ${DISLIN}/libdislin_d.so
ln -s -f ${DISLIN}/lib/dislin_d-11.0.so  ${DISLIN}/libdislnc_d.so.11
ln -s -f ${DISLIN}/libdislin_d.so.11     ${DISLIN}/libdislnc_d.so

ln -s -f ${DISLIN}/java/disjava-11.0.so  ${DISLIN}/libdisjava.so.11
ln -s -f ${DISLIN}/libdisjava.so.11      ${DISLIN}/libdisjava.so

echo "links were created in        "${DISLIN}


