# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.4

CMakeFiles/projet_tristan.dir/Control_JACO.cpp.o: ../include/Control_JACO.h
CMakeFiles/projet_tristan.dir/Control_JACO.cpp.o: ../include/Defined_Macro.h
CMakeFiles/projet_tristan.dir/Control_JACO.cpp.o: ../include/EMG_Sensor.h
CMakeFiles/projet_tristan.dir/Control_JACO.cpp.o: ../include/IMU_Sensor.h
CMakeFiles/projet_tristan.dir/Control_JACO.cpp.o: ../include/KinovaTypes.h
CMakeFiles/projet_tristan.dir/Control_JACO.cpp.o: ../Control_JACO.cpp

CMakeFiles/projet_tristan.dir/Dislin_Scope.cpp.o: ../include/Defined_Macro.h
CMakeFiles/projet_tristan.dir/Dislin_Scope.cpp.o: ../include/Dislin_Scope.h
CMakeFiles/projet_tristan.dir/Dislin_Scope.cpp.o: ../Dislin_Scope.cpp
CMakeFiles/projet_tristan.dir/Dislin_Scope.cpp.o: /usr/local/dislin/discpp.h
CMakeFiles/projet_tristan.dir/Dislin_Scope.cpp.o: /usr/local/dislin/dislin.h

CMakeFiles/projet_tristan.dir/EMG_Sensor.cpp.o: ../include/Defined_Macro.h
CMakeFiles/projet_tristan.dir/EMG_Sensor.cpp.o: ../include/EMG_Sensor.h
CMakeFiles/projet_tristan.dir/EMG_Sensor.cpp.o: ../EMG_Sensor.cpp

CMakeFiles/projet_tristan.dir/IMU_Sensor.cpp.o: ../include/Defined_Macro.h
CMakeFiles/projet_tristan.dir/IMU_Sensor.cpp.o: ../include/IMU_Sensor.h
CMakeFiles/projet_tristan.dir/IMU_Sensor.cpp.o: ../IMU_Sensor.cpp

CMakeFiles/projet_tristan.dir/mySerial.cpp.o: ../include/mySerial.h
CMakeFiles/projet_tristan.dir/mySerial.cpp.o: ../mySerial.cpp

CMakeFiles/projet_tristan.dir/test.cpp.o: ../include/Control_JACO.h
CMakeFiles/projet_tristan.dir/test.cpp.o: ../include/Defined_Macro.h
CMakeFiles/projet_tristan.dir/test.cpp.o: ../include/Dislin_Scope.h
CMakeFiles/projet_tristan.dir/test.cpp.o: ../include/EMG_Sensor.h
CMakeFiles/projet_tristan.dir/test.cpp.o: ../include/IMU_Sensor.h
CMakeFiles/projet_tristan.dir/test.cpp.o: ../include/KinovaTypes.h
CMakeFiles/projet_tristan.dir/test.cpp.o: ../include/mySerial.h
CMakeFiles/projet_tristan.dir/test.cpp.o: ../include/test_print.h
CMakeFiles/projet_tristan.dir/test.cpp.o: ../test.cpp
CMakeFiles/projet_tristan.dir/test.cpp.o: /usr/local/dislin/discpp.h
CMakeFiles/projet_tristan.dir/test.cpp.o: /usr/local/dislin/dislin.h

